/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import apoyo.Cliente;
import apoyo.Prestamo;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author julio
 */
public class Principal extends javax.swing.JFrame {

    //Vector de clientes
    Vector<Cliente> clientes = new Vector();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLienzo = new javax.swing.JPanel();
        jScrollPaneTabla = new javax.swing.JScrollPane();
        jTablaAmortizacion = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItemACliente = new javax.swing.JMenuItem();
        jMenuItemDCliente = new javax.swing.JMenuItem();
        jMenuPrestamos = new javax.swing.JMenu();
        jMenuItemNPrestamo = new javax.swing.JMenuItem();
        jMenuItemTabla = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLienzo.setLayout(new java.awt.BorderLayout());

        jTablaAmortizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Periodo", "Cuota", "Interes", "Capital", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneTabla.setViewportView(jTablaAmortizacion);

        jPanelLienzo.add(jScrollPaneTabla, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelLienzo, java.awt.BorderLayout.CENTER);

        jMenuClientes.setText("Clientes");

        jMenuItemACliente.setText("Añadir cliente");
        jMenuItemACliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemACliente);

        jMenuItemDCliente.setText("Datos del cliente");
        jMenuItemDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDClienteActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItemDCliente);

        jMenuBar1.add(jMenuClientes);

        jMenuPrestamos.setText("Prestamos");

        jMenuItemNPrestamo.setText("Nuevo prestamo");
        jMenuItemNPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNPrestamoActionPerformed(evt);
            }
        });
        jMenuPrestamos.add(jMenuItemNPrestamo);

        jMenuItemTabla.setText("Tabla de amortizacion");
        jMenuItemTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTablaActionPerformed(evt);
            }
        });
        jMenuPrestamos.add(jMenuItemTabla);

        jMenuBar1.add(jMenuPrestamos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAClienteActionPerformed
        // TODO add your handling code here:
        try {
            new AgregarC(this, true, this);
        } catch (Exception ex) {
            System.err.println("Error: " + ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jMenuItemAClienteActionPerformed

    private void jMenuItemNPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNPrestamoActionPerformed
        // TODO add your handling code here:
        try {
            new AgregarP(this, true, this);
        } catch (Exception ex) {
            System.err.println("Error: " + ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jMenuItemNPrestamoActionPerformed

    private void jMenuItemTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTablaActionPerformed
        // TODO add your handling code here:
        try {
            new SelCliente(this, true, this);
        } catch (Exception ex) {
            System.err.println("Error: " + ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jMenuItemTablaActionPerformed

    private void jMenuItemDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDClienteActionPerformed
        // TODO add your handling code here:
        try {
            new Datos(this, true, this);
        } catch (Exception ex) {
            System.err.println("Error: " + ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_jMenuItemDClienteActionPerformed

    public void addClient(Cliente c) {
        this.clientes.add(c);
    }

    public void show(Prestamo p) {
        DefaultTableModel modelo = (DefaultTableModel) jTablaAmortizacion.getModel();
        int a = modelo.getRowCount();
        for (int i = 0; i < a; i++) {
            modelo.removeRow(0);
        }
        float cuota = (p.monto + (p.monto * p.intereses)) / p.meses;
        float interes = (p.monto * p.intereses) / p.meses;
        float capital = (p.monto / p.meses);
        float total = (p.monto + (p.monto * p.intereses));
        Object[] rowData = new Object[5];
        for (int i = 1; i <= p.meses; i++) {
            rowData[0] = i;
            rowData[1] = cuota;
            rowData[2] = interes;
            rowData[3] = capital;
            rowData[4] = total - (cuota * i);

            modelo.addRow(rowData);
        }
        jTablaAmortizacion.setModel(modelo);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenuItem jMenuItemACliente;
    private javax.swing.JMenuItem jMenuItemDCliente;
    private javax.swing.JMenuItem jMenuItemNPrestamo;
    private javax.swing.JMenuItem jMenuItemTabla;
    private javax.swing.JMenu jMenuPrestamos;
    private javax.swing.JPanel jPanelLienzo;
    private javax.swing.JScrollPane jScrollPaneTabla;
    private javax.swing.JTable jTablaAmortizacion;
    // End of variables declaration//GEN-END:variables
}
